/**
 * Generates the GitHub wiki from the repository's docs and website.
 *
 * - README.md is split into one page per `##` section; the part above the first section
 *   becomes the Home page intro.
 * - The content sections of web/index.html (how it works, supported markup, the VS Code
 *   promo and the FAQ) are converted to Markdown pages.
 * - CHANGELOG.md becomes the Changelog page.
 *
 * Usage: node scripts/generate-wiki.mjs [outDir]   (default: wiki/)
 *
 * Every `.md` file in outDir is replaced, so the wiki always mirrors the sources. Anything
 * else there, such as the wiki's own `.git`, is left alone.
 */
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { parse } from 'node-html-parser';

const root = fileURLToPath(new URL('..', import.meta.url));
const outDir = new URL(`${process.argv[2] ?? 'wiki'}/`, `file://${process.cwd()}/`);

const REPO_URL = 'https://github.com/TautvydasDerzinskas/vscode-html-to-css';
const BLOB_URL = `${REPO_URL}/blob/main/`;
const RAW_URL = 'https://raw.githubusercontent.com/TautvydasDerzinskas/vscode-html-to-css/main/';
const SITE_URL = 'https://tautvydasderzinskas.github.io/vscode-html-to-css/';

const GENERATED_NOTE =
  '<!-- Generated by scripts/generate-wiki.mjs from README.md, CHANGELOG.md and web/index.html. Edit those instead: changes made here are overwritten. -->';

/** GitHub's heading anchor: lower-case, punctuation dropped, spaces to hyphens. */
const toAnchor = heading =>
  heading
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s_-]/gu, '')
    .trim()
    .replace(/\s/g, '-');

/** Wiki page name for a heading. Dots are dropped: GitHub wiki URLs treat them as extensions. */
const toPageName = heading =>
  heading
    .replace(/[./\\?#%:]/g, '')
    .trim()
    .replace(/\s+/g, '-');

// ---------------------------------------------------------------------------------------------
// README -> pages

/** README sections that go on the Home page instead of a page of their own. */
const HOME_SECTIONS = new Set(['License', 'Support']);

function splitReadme(markdown) {
  const lines = markdown.split('\n');
  const sections = [];
  let current = { heading: null, lines: [] };
  let inFence = false;

  for (const line of lines) {
    if (/^(```|~~~)/.test(line)) inFence = !inFence;
    const match = !inFence && /^## (.+)$/.exec(line);
    if (match) {
      sections.push(current);
      current = { heading: match[1].trim(), lines: [] };
    } else {
      current.lines.push(line);
    }
  }
  sections.push(current);

  for (const section of sections) section.body = section.lines.join('\n').trim();
  return sections;
}

/**
 * Maps every README anchor to where it lives in the wiki: `##` headings to their page, and
 * deeper headings to an anchor on that page.
 */
function buildAnchorMap(sections) {
  const anchors = new Map();
  for (const section of sections) {
    if (!section.heading) continue;
    const page = HOME_SECTIONS.has(section.heading) ? 'Home' : toPageName(section.heading);
    anchors.set(toAnchor(section.heading), page);
    for (const match of section.body.matchAll(/^#{3,6} (.+)$/gm)) {
      anchors.set(toAnchor(match[1]), `${page}#${toAnchor(match[1])}`);
    }
  }
  return anchors;
}

/** Points README-relative links and images at GitHub, and README anchors at wiki pages. */
function rewriteLinks(markdown, anchors) {
  const resolve = (target, isImage) => {
    if (/^[a-z]+:|^\/\//i.test(target)) return target;
    if (target.startsWith('#')) return anchors.get(target.slice(1)) ?? `Home${target}`;
    const path = target.replace(/^\.?\//, '');
    return (isImage ? RAW_URL : BLOB_URL) + path;
  };

  return (
    markdown
      // Markdown links and images, skipping fenced code.
      .split(/(^```[\s\S]*?^```)/m)
      .map((chunk, index) =>
        index % 2
          ? chunk
          : chunk
              .replace(
                /(!?)\[([^\]]*)\]\(([^)\s]+)\)/g,
                (_, bang, text, target) => `${bang}[${text}](${resolve(target, Boolean(bang))})`
              )
              .replace(
                /(<img[^>]*\ssrc=")([^"]+)"/g,
                (_, before, src) => `${before}${resolve(src, true)}"`
              )
              .replace(
                /(<a[^>]*\shref=")([^"]+)"/g,
                (_, before, href) => `${before}${resolve(href, false)}"`
              )
      )
      .join('')
  );
}

// ---------------------------------------------------------------------------------------------
// Website HTML -> Markdown

const inline = node => {
  if (node.nodeType === 3) return node.text.replace(/\s+/g, ' ');
  if (node.nodeType !== 1) return '';

  const content = () => node.childNodes.map(inline).join('');
  switch (node.tagName.toLowerCase()) {
    case 'strong':
    case 'b':
      return `**${content().trim()}**`;
    case 'em':
    case 'i':
      return `_${content().trim()}_`;
    case 'code': {
      const text = node.text;
      return text.includes('`') ? `\`\` ${text} \`\`` : `\`${text}\``;
    }
    case 'kbd':
      return `<kbd>${node.text.trim()}</kbd>`;
    case 'a': {
      const href = node.getAttribute('href') ?? '';
      const target = /^[a-z]+:/i.test(href) ? href : new URL(href, SITE_URL).href;
      return `[${content().trim()}](${target})`;
    }
    case 'br':
      return '\n';
    default:
      return content();
  }
};

const inlineText = node => inline(node).replace(/\s+/g, ' ').trim();

/** Converts a block of the website's markup to Markdown. `depth` shifts heading levels. */
function blocks(node, depth = 0) {
  const out = [];
  for (const child of node.childNodes) {
    if (child.nodeType !== 1) {
      const text = child.nodeType === 3 ? child.text.trim() : '';
      if (text) out.push(text);
      continue;
    }
    const tag = child.tagName.toLowerCase();
    const heading = /^h([1-6])$/.exec(tag);
    if (heading) {
      out.push(`${'#'.repeat(Math.min(6, Number(heading[1]) + depth))} ${inlineText(child)}`);
    } else if (tag === 'p') {
      out.push(inlineText(child));
    } else if (tag === 'ul' || tag === 'ol') {
      const items = child.childNodes.filter(item => item.nodeType === 1 && item.tagName === 'LI');
      out.push(
        items
          .map((item, index) => {
            const marker = tag === 'ol' ? `${index + 1}.` : '-';
            // A list item holding a heading and a paragraph reads as "**Title** — text".
            const title = item.querySelector('h1, h2, h3, h4, h5, h6');
            const text = title
              ? `**${inlineText(title)}** — ${item.querySelectorAll('p').map(inlineText).join(' ')}`
              : inlineText(item);
            return `${marker} ${text}`;
          })
          .join('\n')
      );
    } else if (tag === 'details') {
      const summary = child.querySelector('summary');
      out.push(`${'#'.repeat(3 + depth)} ${inlineText(summary)}`);
      summary.remove();
      out.push(...blocks(child, depth));
    } else if (tag === 'img' || tag === 'script' || tag === 'form') {
      continue;
    } else {
      out.push(...blocks(child, depth));
    }
  }
  return out.filter(Boolean);
}

const toMarkdown = (node, depth) => blocks(node, depth).join('\n\n');

function websitePages(html) {
  const document = parse(html);
  const section = selector => {
    const found = document.querySelector(selector);
    if (!found) throw new Error(`web/index.html has no ${selector}`);
    return found;
  };

  const hero = section('.hero');
  const how = section('section[aria-labelledby="how-heading"]');
  const supported = section('#supported');
  const vscode = section('#vscode');
  const faq = section('#faq');

  // Each page gets its own title, so drop the section's own h2 and lift its h3s to h2.
  const body = node => {
    node.querySelector('h2')?.remove();
    return toMarkdown(node, -1);
  };

  return {
    'Online-Converter': [
      `[**Open the online converter →**](${SITE_URL})`,
      inlineText(hero.querySelector('.hero__lead')),
      `## ${inlineText(how.querySelector('h2'))}`,
      body(how),
      `## Deep links`,
      `- [${SITE_URL}](${SITE_URL}) opens HTML → CSS.\n- [${SITE_URL}#css-to-html](${SITE_URL}#css-to-html) opens CSS → HTML.`,
      `Every option in the sidebar is also an extension setting — see [Settings](Settings).`,
    ],
    'Supported-Languages': [body(supported)],
    'VS-Code-Extension': [
      // The promo is written from the website's point of view.
      body(vscode).replace(/^This page runs/, `The [online converter](${SITE_URL}) runs`),
      'See [Usage](Usage) for every command, and [Settings](Settings) for the options.',
    ],
    FAQ: [body(faq)],
  };
}

// ---------------------------------------------------------------------------------------------
// Assemble

/** `Online-Converter` -> `[Online Converter](Online-Converter)`. */
const link = name => `[${name.replace(/-/g, ' ')}](${name})`;

async function main() {
  const [readme, changelog, html, packageJson] = await Promise.all([
    readFile(`${root}README.md`, 'utf8'),
    readFile(`${root}CHANGELOG.md`, 'utf8'),
    readFile(`${root}web/index.html`, 'utf8'),
    readFile(`${root}package.json`, 'utf8').then(JSON.parse),
  ]);

  const sections = splitReadme(readme);
  const anchors = buildAnchorMap(sections);
  const [intro, ...rest] = sections;

  /** @type {Map<string, string>} page name -> Markdown */
  const pages = new Map();
  const readmePages = [];
  const homeExtras = [];

  for (const section of rest) {
    const body = rewriteLinks(section.body, anchors);
    if (HOME_SECTIONS.has(section.heading)) {
      homeExtras.push(`## ${section.heading}\n\n${body}`);
    } else {
      const name = toPageName(section.heading);
      readmePages.push({ name, title: section.heading });
      pages.set(name, body);
    }
  }

  const website = websitePages(html);
  for (const [name, parts] of Object.entries(website)) {
    pages.set(name, parts.join('\n\n'));
  }

  pages.set('Changelog', changelog.replace(/^# .*\n+/, '').trim());

  const websiteNames = Object.keys(website);

  pages.set(
    'Home',
    [
      rewriteLinks(intro.body, anchors),
      '## Contents',
      `**The extension**\n\n${readmePages.map(page => `- [${page.title}](${page.name})`).join('\n')}`,
      `**The website**\n\n${websiteNames.map(name => `- ${link(name)}`).join('\n')}`,
      `**Project**\n\n- ${link('Changelog')}\n- [Source code](${REPO_URL})`,
      ...homeExtras,
    ].join('\n\n')
  );

  pages.set(
    '_Sidebar',
    [
      `**[${packageJson.displayName}](Home)**`,
      `**Extension**\n\n${readmePages.map(page => `- [${page.title}](${page.name})`).join('\n')}`,
      `**Website**\n\n${websiteNames.map(name => `- ${link(name)}`).join('\n')}`,
      `**Project**\n\n- ${link('Changelog')}\n- [Try it online](${SITE_URL})\n- [Report an issue](${REPO_URL}/issues)`,
    ].join('\n\n')
  );

  pages.set(
    '_Footer',
    `Generated from the [repository](${REPO_URL}) docs and [website](${SITE_URL}) — edit those, not the wiki. MIT licensed.`
  );

  await mkdir(outDir, { recursive: true });
  const existing = await readdir(outDir);
  await Promise.all(
    existing.filter(file => file.endsWith('.md')).map(file => rm(new URL(file, outDir)))
  );
  await Promise.all(
    [...pages].map(([name, markdown]) => {
      const note = name.startsWith('_') ? '' : `${GENERATED_NOTE}\n\n`;
      return writeFile(new URL(`${name}.md`, outDir), `${note}${markdown.trim()}\n`);
    })
  );

  console.log(`Wrote ${pages.size} wiki pages to ${fileURLToPath(outDir)}`);
}

await main();
